#ifndef MYLIB_RBTREE_H
#define MYLIB_RBTREE_H

#include "c_lib/base.h"
#include "c_lib/rbtree.h"

#define mylib_rbtree c_lib_rbtree
#define mylib_rbtree_node c_lib_rbtree_node
#define mylib_rbtree_create c_lib_rbtree_create
#define mylib_rbtree_destroy c_lib_rbtree_destroy
#define mylib_rbtree_clear c_lib_rbtree_clear
#define mylib_rbtree_insert c_lib_rbtree_insert
#define mylib_rbtree_delete c_lib_rbtree_delete
#define mylib_rbtree_search c_lib_rbtree_search
#define mylib_rbtree_update c_lib_rbtree_update
#define mylib_rbtree_min c_lib_rbtree_min
#define mylib_rbtree_max c_lib_rbtree_max
#define mylib_rbtree_count c_lib_rbtree_count
#define mylib_rbtree_is_empty c_lib_rbtree_is_empty
#define mylib_rbtree_inorder c_lib_rbtree_inorder
#define mylib_rbtree_preorder c_lib_rbtree_preorder
#define mylib_rbtree_postorder c_lib_rbtree_postorder
#define mylib_rbtree_lower_bound c_lib_rbtree_lower_bound
#define mylib_rbtree_upper_bound c_lib_rbtree_upper_bound
#define mylib_rbtree_color c_lib_rbtree_color
#define MYLIB_RBTREE_BLACK C_LIB_RBTREE_BLACK
#define MYLIB_RBTREE_RED C_LIB_RBTREE_RED
#define mylib_rbtree_key_cmp c_lib_rbtree_key_cmp
#define mylib_rbtree_visit_fn c_lib_rbtree_visit_fn

#define MYLIB_CONTAINER_OF c_lib_container_of

#endif